### ISSUE TITLE
Add Python basics examples

### ISSUE THREAD

**Issue by revix-0** [revix-0/Programming_Languages#15]
Same samples like C but in python. Be sure to comment those.

**Comment by HAMMADMOBIN** [comment]
# Comment in python
#Hello I am comment

# print hello world
print('Hello, World) 

# Print the sum of 7 and 10
print (7+10)

# Define a variable 
height = 1.79
weight = 68.7

# check type of variable
type(height )

# Define the list in python
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]

# sublist in Python
fam2 = [["liz",1.73],
       ["emma",1.68],
       ["mom",1.71],
       ["dad",1.89]]

# subsetting and accessing the lists       
fam[3] 

fam[3:5] ##  Apparently it selects only 3 elements and 4 elements it works [start : end -1] [inclusive : exclusive] 

# dictonaries {keys:values}
world = {"afghanistan":30.55,"albania":2.77,"algeria":39.21}
world["albania"]

# For loop in python
for i in range(10):
    print(i)

**Comment by ankurup3** [comment]
Hey, Can I work on this issue ? 
(I am a beginner in Open Source)
